version: '3.1'

services:
  postgresql:
    container_name: postgresql
    image: postgres:11.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'project_name'
    volumes:
      - ./data/docker/postgresql/data:/var/lib/postgresql/data
      - ./src/frameworks/database/seeds:/docker-entrypoint-initdb.d
